return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = { "lua",
      "python",
      "c",
      "cpp",
      "bibtex",
      "cmake",
      "css",
      "json",
      "javascript",
      "html",
      "markdown",
      "make",
      "latex",
      "fortran",
      "git_config",
      "git_rebase",
      "gitignore",
      "gitcommit",
      "julia",
      "ninja",
      "regex",
      "scss",
      "yaml",
      "toml",
      "astro",
      "rust",
      "typescript",
      "vim",
      "vimdoc"
    },
  },
}
